version: '3.9'

services:
  crawler:
    container_name: crawler
    build:
      dockerfile: ./compose/crawler/Dockerfile
      context: .
    command: tail -F anything
    volumes:
      - ./src/:/app/src/

  redis:
    image: redis:6
    container_name: redis
    environment:
      - PORT:${REDIS_PORT}
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "--raw",
          "incr",
          "-p",
          "${REDIS_PORT}",
          "ping"
        ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    command: /bin/bash -c "redis-server --port ${REDIS_PORT}"
